version: '2'
services:

  php:
    build:
      dockerfile: Dockerfile-${DOCKERFILE_FLAVOUR}
      context: 'php'
      args:
        - PHP_BASE_IMAGE_VERSION=${PHP_BASE_IMAGE_VERSION}
    image: ${PHP_IMAGE_NAME}:${PHP_BASE_IMAGE_VERSION}${PHP_IMAGE_VERSION_SUFFIX}
    container_name: app
    environment:
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - PHP_ENABLE_XDEBUG
      - TEST_RUNTIME_PATH=/tmp/runtime
      - MYSQL_DSN=${DB_MYSQL_DSN}${DB_DATABASE}
      - MYSQL_USERNAME=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      #- ./tests:/tests:delegated
      # Framework testing
      #- ./_host-volumes/yii2:/yii2:delegated
      # Application testing
      - ./_host-volumes/app:/app:delegated
      # Composer cache
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
    restart: always
    depends_on:
      - db

  db:
    build:
      dockerfile: Dockerfile
      context: 'db'
    image: ${MYSQL_IMAGE_NAME}
    volumes:
      - ./_host-volumes/db:/var/lib/mysql
      - ./db/config.cnf:/etc/mysql/conf.d/config.conf
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
